import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  mainSidebar: [
    {type: 'doc', id: 'index', label: 'Overview'},
    {
      type: 'category',
      label: 'Getting Started',
      items: [
        'getting-started/installation',
        'getting-started/marketplace',
        'getting-started/configuration',
        'getting-started/first-use',
        'getting-started/docker',
      ],
    },
    {
      type: 'category',
      label: 'Guides',
      items: [
        'guides/analyze-a-codebase',
        'guides/find-external-usages',
        'guides/inspect-nuget-packages',
        'guides/refactor-with-code-actions',
        'guides/understand-di-wiring',
      ],
    },
    {type: 'doc', id: 'external-assemblies', label: 'External Assemblies'},
    {type: 'doc', id: 'faq', label: 'FAQ'},
    {
      type: 'category',
      label: 'Tool Reference',
      link: {type: 'generated-index', title: 'Tool Reference'},
      items: [{type: 'autogenerated', dirName: 'tools'}],
    },
  ],
};

export default sidebars;
