using System.Collections.Concurrent;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Text;
using RoslynCodeLens.Analysis;
using RoslynCodeLens.Tests.Fixtures;

namespace RoslynCodeLens.Tests.Analysis;

public class SolutionScannerTests
{
    private const string Linked = """
        namespace Demo;
        public class Shared { public int Value; }
        """;

    [Fact]
    public void PathlessTree_InTwoCompilations_YieldedOnce()
    {
        // The bug this pins: a path-keyed dedupe never adds a pathless tree to its set, so the same
        // in-memory document present in two compilations is walked — and counted — twice.
        var (loaded, resolver) = PathlessInTwoProjects(Linked, Linked);

        var scans = SolutionScanner.EnumerateTrees(loaded, resolver).ToList();

        Assert.Single(scans);
        Assert.Equal(string.Empty, Assert.Single(scans).Tree.FilePath);
    }

    [Fact]
    public void PathlessTrees_WithDifferentContent_BothYielded()
    {
        // The dedupe must key on the tree's identity, not merely on "has no path".
        var (loaded, resolver) = PathlessInTwoProjects(
            Linked, "namespace Demo; public class Other { }");

        var scans = SolutionScanner.EnumerateTrees(loaded, resolver).ToList();

        Assert.Equal(2, scans.Count);
    }

    [Fact]
    public void LinkedFile_WithoutDiscriminator_YieldedOnce()
    {
        var (loaded, resolver) = RenameTestWorkspace.Create(
            ("ProjA", [("Shared.cs", Linked)]),
            ("ProjB", [("Shared.cs", Linked)]));

        var scans = SolutionScanner.EnumerateTrees(loaded, resolver).ToList();

        var scan = Assert.Single(scans);
        // First-one-wins attribution must be a property of the solution, not of dictionary order.
        Assert.Equal("ProjA", scan.ProjectName);
    }

    [Fact]
    public void LinkedFile_WithDiscriminator_YieldedPerScope()
    {
        var (loaded, resolver) = RenameTestWorkspace.Create(
            ("ProjA", [("Shared.cs", Linked)]),
            ("ProjB", [("Shared.cs", Linked)]));

        var scans = SolutionScanner
            .EnumerateTrees(loaded, resolver, scopeDiscriminator: (projectName, _) => projectName)
            .ToList();

        Assert.Equal(["ProjA", "ProjB"], scans.Select(s => s.ProjectName).ToArray());
    }

    [Fact]
    public void ProjectFilter_SkipsCompilationBeforeAnyTreeWork()
    {
        var (loaded, resolver) = RenameTestWorkspace.Create(
            ("ProjA", [("A.cs", "namespace A; public class Aa { }")]),
            ("ProjB", [("B.cs", "namespace B; public class Bb { }")]));

        var asked = new List<string>();
        var scans = SolutionScanner
            .EnumerateTrees(loaded, resolver, projectFilter: name =>
            {
                asked.Add(name);
                return name == "ProjB";
            })
            .ToList();

        var scan = Assert.Single(scans);
        Assert.Equal("ProjB", scan.ProjectName);
        Assert.Equal(["ProjA", "ProjB"], asked);
    }

    [Fact]
    public void GeneratedTrees_AreSkipped()
    {
        var (loaded, resolver) = RenameTestWorkspace.Create(
            ("Real.cs", "namespace Demo; public class Real { }"),
            ("Machine.g.cs", "namespace Demo; public class Machine { }"),
            ("Header.cs", "// <auto-generated>\nnamespace Demo; public class Header { }"));

        var scans = SolutionScanner.EnumerateTrees(loaded, resolver).ToList();

        Assert.Equal(["Real.cs"], scans.Select(s => s.Tree.FilePath).ToArray());
    }

    [Fact]
    public void Cancellation_IsObserved()
    {
        var (loaded, resolver) = RenameTestWorkspace.Create(
            ("A.cs", "namespace A; public class Aa { }"),
            ("B.cs", "namespace B; public class Bb { }"));

        using var cts = new CancellationTokenSource();
        cts.Cancel();

        Assert.Throws<OperationCanceledException>(() =>
            SolutionScanner.EnumerateTrees(loaded, resolver, cancellationToken: cts.Token).ToList());
    }

    [Fact]
    public void Cancellation_BetweenTrees_IsObserved()
    {
        var (loaded, resolver) = RenameTestWorkspace.Create(
            ("A.cs", "namespace A; public class Aa { }"),
            ("B.cs", "namespace B; public class Bb { }"));

        using var cts = new CancellationTokenSource();

        Assert.Throws<OperationCanceledException>(() =>
        {
            foreach (var _ in SolutionScanner.EnumerateTrees(
                         loaded, resolver, cancellationToken: cts.Token))
            {
                cts.Cancel();
            }
        });
    }

    [Fact]
    public void SemanticModel_IsCreatedOnlyWhenAsked_AndOnlyOnce()
    {
        var (loaded, resolver) = RenameTestWorkspace.Create(
            ("A.cs", "namespace A; public class Aa { }"));

        var created = 0;
        var scan = Assert.Single(SolutionScanner.EnumerateTrees(
            loaded, resolver,
            modelFactory: (compilation, tree) =>
            {
                created++;
                return compilation.GetSemanticModel(tree);
            }));

        // Enumeration itself must bind nothing: callers filter trees on syntactic grounds
        // (check_architecture drops a tree after reading its declared namespaces) and binding one
        // that is about to be discarded is the most expensive thing such a scan can do.
        Assert.Equal(0, created);

        var first = scan.SemanticModel();
        Assert.Equal(1, created);

        // ...and asking twice must not pay twice. A caller reaching for the model in two places in
        // its loop body wants one model, so the accessor memoises.
        var second = scan.SemanticModel();
        Assert.Equal(1, created);
        Assert.Same(first, second);
        Assert.Same(scan.Tree, first.SyntaxTree);
    }

    [Fact]
    public void DuplicateTree_IsNeverParsed()
    {
        // The same file present in two compilations — a linked file, or one project multi-targeted
        // across frameworks. Deduping only AFTER building the ScanTree would realise a root per
        // compilation and discard all but the first: four TFMs, four parses, three thrown away.
        var (loaded, resolver) = RenameTestWorkspace.Create(
            ("ProjA", [("Shared.cs", Linked)]),
            ("ProjB", [("Shared.cs", Linked)]));

        var rooted = 0;
        var scans = SolutionScanner.EnumerateTrees(
            loaded, resolver,
            rootFactory: (tree, ct) =>
            {
                rooted++;
                return tree.GetRoot(ct);
            })
            .ToList();

        Assert.Single(scans);
        Assert.Equal(1, rooted);
    }

    /// <summary>
    /// One project per source, each compilation holding a tree with NO file path.
    /// RenameTestWorkspace cannot express this — a workspace document always carries a path, and
    /// Roslyn falls back to the document name even when one is passed explicitly as null — so the
    /// compilations are built straight from parsed trees, which is what an in-memory document or
    /// generator output looks like to a scan.
    /// </summary>
    private static (LoadedSolution Loaded, SymbolResolver Resolver) PathlessInTwoProjects(
        params string[] sourcesPerProject)
    {
        var workspace = new AdhocWorkspace();
        var solution = workspace.CurrentSolution;
        var compilations = new ConcurrentDictionary<ProjectId, Compilation>();
        var reference = MetadataReference.CreateFromFile(typeof(object).Assembly.Location);

        for (var i = 0; i < sourcesPerProject.Length; i++)
        {
            var projectId = ProjectId.CreateNewId();
            var name = $"Proj{i}";
            solution = solution.AddProject(ProjectInfo.Create(
                projectId, VersionStamp.Create(), name, name, LanguageNames.CSharp,
                compilationOptions: new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary)));

            compilations[projectId] = CSharpCompilation.Create(
                name,
                [CSharpSyntaxTree.ParseText(SourceText.From(sourcesPerProject[i]))],
                [reference],
                new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));
        }

        var loaded = new LoadedSolution { Solution = solution, Compilations = compilations };
        return (loaded, new SymbolResolver(loaded));
    }
}
