using System.Collections.Concurrent;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Text;
using RoslynCodeLens.Analysis;
using RoslynCodeLens.Tests.Fixtures;

namespace RoslynCodeLens.Tests.Analysis;

public class SolutionScannerTests
{
    private const string Linked = """
        namespace Demo;
        public class Shared { public int Value; }
        """;

    [Fact]
    public void PathlessTree_InTwoCompilations_YieldedOnce()
    {
        // The bug this pins: a path-keyed dedupe never adds a pathless tree to its set, so the same
        // in-memory document present in two compilations is walked — and counted — twice.
        var (loaded, resolver) = PathlessInTwoProjects(Linked, Linked);

        var scans = SolutionScanner.EnumerateTrees(loaded, resolver).ToList();

        Assert.Single(scans);
        Assert.Equal(string.Empty, Assert.Single(scans).Tree.FilePath);
    }

    [Fact]
    public void PathlessTrees_WithDifferentContent_BothYielded()
    {
        // The dedupe must key on the tree's identity, not merely on "has no path".
        var (loaded, resolver) = PathlessInTwoProjects(
            Linked, "namespace Demo; public class Other { }");

        var scans = SolutionScanner.EnumerateTrees(loaded, resolver).ToList();

        Assert.Equal(2, scans.Count);
    }

    [Fact]
    public void LinkedFile_WithoutDiscriminator_YieldedOnce()
    {
        var (loaded, resolver) = RenameTestWorkspace.Create(
            ("ProjA", [("Shared.cs", Linked)]),
            ("ProjB", [("Shared.cs", Linked)]));

        var scans = SolutionScanner.EnumerateTrees(loaded, resolver).ToList();

        var scan = Assert.Single(scans);
        // First-one-wins attribution must be a property of the solution, not of dictionary order.
        Assert.Equal("ProjA", scan.ProjectName);
    }

    [Fact]
    public void LinkedFile_WithDiscriminator_YieldedPerScope()
    {
        var (loaded, resolver) = RenameTestWorkspace.Create(
            ("ProjA", [("Shared.cs", Linked)]),
            ("ProjB", [("Shared.cs", Linked)]));

        var scans = SolutionScanner
            .EnumerateTrees(loaded, resolver, scopeDiscriminator: (projectName, _) => projectName)
            .ToList();

        Assert.Equal(["ProjA", "ProjB"], scans.Select(s => s.ProjectName).ToArray());
    }

    [Fact]
    public void ProjectFilter_SkipsCompilationBeforeAnyTreeWork()
    {
        var (loaded, resolver) = RenameTestWorkspace.Create(
            ("ProjA", [("A.cs", "namespace A; public class Aa { }")]),
            ("ProjB", [("B.cs", "namespace B; public class Bb { }")]));

        var asked = new List<string>();
        var scans = SolutionScanner
            .EnumerateTrees(loaded, resolver, projectFilter: (_, name) =>
            {
                asked.Add(name);
                return name == "ProjB";
            })
            .ToList();

        var scan = Assert.Single(scans);
        Assert.Equal("ProjB", scan.ProjectName);
        Assert.Equal(["ProjA", "ProjB"], asked);
    }

    /// <summary>
    /// The filter receives the project id as well as the name because a name does not identify a
    /// project — two in different folders can share one, which is the same reason the enumeration
    /// order cannot tie-break on name alone. A name-only filter excluding one of them (a test
    /// project, say) would silently exclude the other too.
    /// </summary>
    [Fact]
    public void ProjectFilter_CanDistinguishSameNamedProjects()
    {
        var (loaded, resolver) = RenameTestWorkspace.Create(
            ("Common", [("A.cs", "namespace A; public class Aa { }")]),
            ("Common", [("B.cs", "namespace B; public class Bb { }")]));

        var excluded = loaded.Solution.Projects.First().Id;

        var scans = SolutionScanner
            .EnumerateTrees(loaded, resolver, projectFilter: (id, _) => id != excluded)
            .ToList();

        var scan = Assert.Single(scans);
        Assert.NotEqual(excluded, scan.ProjectId);
    }

    [Fact]
    public void GeneratedTrees_AreSkipped()
    {
        var (loaded, resolver) = RenameTestWorkspace.Create(
            ("Real.cs", "namespace Demo; public class Real { }"),
            ("Machine.g.cs", "namespace Demo; public class Machine { }"),
            ("Header.cs", "// <auto-generated>\nnamespace Demo; public class Header { }"));

        var scans = SolutionScanner.EnumerateTrees(loaded, resolver).ToList();

        Assert.Equal(["Real.cs"], scans.Select(s => s.Tree.FilePath).ToArray());
    }

    /// <summary>
    /// The opt-in for callers that report what the program DOES rather than what a human should
    /// change. DI registration is the motivating case: one emitted by a source generator wires up
    /// the container exactly as a hand-written one does, so skipping it makes the answer wrong.
    /// Both detection routes — the <c>.g.cs</c> path and the <c>&lt;auto-generated&gt;</c> header —
    /// must be covered, since they are separate branches.
    /// </summary>
    [Fact]
    public void GeneratedTrees_AreIncluded_WhenOptedIn()
    {
        var (loaded, resolver) = RenameTestWorkspace.Create(
            ("Real.cs", "namespace Demo; public class Real { }"),
            ("Machine.g.cs", "namespace Demo; public class Machine { }"),
            ("Header.cs", "// <auto-generated>\nnamespace Demo; public class Header { }"));

        var scans = SolutionScanner
            .EnumerateTrees(loaded, resolver, includeGenerated: true)
            .ToList();

        Assert.Equal(
            ["Header.cs", "Machine.g.cs", "Real.cs"],
            scans.Select(s => s.Tree.FilePath).OrderBy(p => p, StringComparer.Ordinal).ToArray());
    }

    [Fact]
    public void Cancellation_IsObserved()
    {
        var (loaded, resolver) = RenameTestWorkspace.Create(
            ("A.cs", "namespace A; public class Aa { }"),
            ("B.cs", "namespace B; public class Bb { }"));

        using var cts = new CancellationTokenSource();
        cts.Cancel();

        Assert.Throws<OperationCanceledException>(() =>
            SolutionScanner.EnumerateTrees(loaded, resolver, cancellationToken: cts.Token).ToList());
    }

    [Fact]
    public void Cancellation_BetweenTrees_IsObserved()
    {
        var (loaded, resolver) = RenameTestWorkspace.Create(
            ("A.cs", "namespace A; public class Aa { }"),
            ("B.cs", "namespace B; public class Bb { }"));

        using var cts = new CancellationTokenSource();

        Assert.Throws<OperationCanceledException>(() =>
        {
            foreach (var _ in SolutionScanner.EnumerateTrees(
                         loaded, resolver, cancellationToken: cts.Token))
            {
                cts.Cancel();
            }
        });
    }

    [Fact]
    public void SemanticModel_IsCreatedOnlyWhenAsked_AndOnlyOnce()
    {
        var (loaded, resolver) = RenameTestWorkspace.Create(
            ("A.cs", "namespace A; public class Aa { }"));

        var created = 0;
        var scan = Assert.Single(SolutionScanner.EnumerateTrees(
            loaded, resolver,
            modelFactory: (compilation, tree) =>
            {
                created++;
                return compilation.GetSemanticModel(tree);
            }));

        // Enumeration itself must bind nothing: callers filter trees on syntactic grounds
        // (check_architecture drops a tree after reading its declared namespaces) and binding one
        // that is about to be discarded is the most expensive thing such a scan can do.
        Assert.Equal(0, created);

        var first = scan.SemanticModel();
        Assert.Equal(1, created);

        // ...and asking twice must not pay twice. A caller reaching for the model in two places in
        // its loop body wants one model, so the accessor memoises.
        var second = scan.SemanticModel();
        Assert.Equal(1, created);
        Assert.Same(first, second);
        Assert.Same(scan.Tree, first.SyntaxTree);
    }

    [Fact]
    public void DuplicateTree_IsNeverParsed()
    {
        // The same file present in two compilations — a linked file, or one project multi-targeted
        // across frameworks. Deduping only AFTER building the ScanTree would realise a root per
        // compilation and discard all but the first: four TFMs, four parses, three thrown away.
        var (loaded, resolver) = RenameTestWorkspace.Create(
            ("ProjA", [("Shared.cs", Linked)]),
            ("ProjB", [("Shared.cs", Linked)]));

        var rooted = 0;
        var scans = SolutionScanner.EnumerateTrees(
            loaded, resolver,
            rootFactory: (tree, ct) =>
            {
                rooted++;
                return tree.GetRoot(ct);
            })
            .ToList();

        Assert.Single(scans);
        Assert.Equal(1, rooted);
    }

    [Fact]
    public void SameNamedProjects_AreOrderedStablyAcrossLoads()
    {
        // ProjectId.Id is a Guid minted afresh on every workspace load, so tiebreaking on it is
        // exactly as arbitrary as the ConcurrentDictionary order it was meant to replace — and two
        // projects sharing a Name is the ONLY case the tiebreak decides. The .csproj path is
        // unique within a solution and survives reloads.
        var winners = new HashSet<string>(StringComparer.Ordinal);

        for (var i = 0; i < 20; i++)
        {
            // Alternate insertion order too, so a pass cannot come from the projects happening to
            // be added in the same order every time.
            var (loaded, resolver, csprojByProject) = SameNamedProjects(reversed: i % 2 == 1);

            var scan = Assert.Single(SolutionScanner.EnumerateTrees(loaded, resolver));
            winners.Add(csprojByProject[scan.ProjectId]);
        }

        Assert.Equal(@"C:\sln\A\Shared.csproj", Assert.Single(winners));
    }

    /// <summary>
    /// Two projects with the SAME name and assembly name, differing only in .csproj path, sharing
    /// one linked source file. RenameTestWorkspace cannot express this — it gives projects no
    /// FilePath at all.
    /// </summary>
    private static (LoadedSolution Loaded, SymbolResolver Resolver, Dictionary<ProjectId, string> CsprojByProject)
        SameNamedProjects(bool reversed)
    {
        var workspace = new AdhocWorkspace();
        var solution = workspace.CurrentSolution;
        var compilations = new ConcurrentDictionary<ProjectId, Compilation>();
        var csprojByProject = new Dictionary<ProjectId, string>();

        string[] csprojPaths = [@"C:\sln\A\Shared.csproj", @"C:\sln\B\Shared.csproj"];
        foreach (var csproj in reversed ? csprojPaths.Reverse() : csprojPaths)
        {
            var projectId = ProjectId.CreateNewId();
            csprojByProject[projectId] = csproj;

            solution = solution
                .AddProject(ProjectInfo.Create(
                    projectId, VersionStamp.Create(), "Shared", "Shared", LanguageNames.CSharp,
                    filePath: csproj,
                    compilationOptions: new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary))
                    .WithMetadataReferences(
                        [MetadataReference.CreateFromFile(typeof(object).Assembly.Location)]))
                .AddDocument(
                    DocumentId.CreateNewId(projectId), "Shared.cs",
                    SourceText.From(Linked), filePath: @"C:\sln\Shared.cs");
        }

        foreach (var projectId in csprojByProject.Keys)
        {
            compilations[projectId] = solution.GetProject(projectId)!
                .GetCompilationAsync().GetAwaiter().GetResult()!;
        }

        var loaded = new LoadedSolution { Solution = solution, Compilations = compilations };
        return (loaded, new SymbolResolver(loaded), csprojByProject);
    }

    /// <summary>
    /// One project per source, each compilation holding a tree with NO file path.
    /// RenameTestWorkspace cannot express this — a workspace document always carries a path, and
    /// Roslyn falls back to the document name even when one is passed explicitly as null — so the
    /// compilations are built straight from parsed trees, which is what an in-memory document or
    /// generator output looks like to a scan.
    /// </summary>
    private static (LoadedSolution Loaded, SymbolResolver Resolver) PathlessInTwoProjects(
        params string[] sourcesPerProject)
    {
        var workspace = new AdhocWorkspace();
        var solution = workspace.CurrentSolution;
        var compilations = new ConcurrentDictionary<ProjectId, Compilation>();
        var reference = MetadataReference.CreateFromFile(typeof(object).Assembly.Location);

        for (var i = 0; i < sourcesPerProject.Length; i++)
        {
            var projectId = ProjectId.CreateNewId();
            var name = $"Proj{i}";
            solution = solution.AddProject(ProjectInfo.Create(
                projectId, VersionStamp.Create(), name, name, LanguageNames.CSharp,
                compilationOptions: new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary)));

            compilations[projectId] = CSharpCompilation.Create(
                name,
                [CSharpSyntaxTree.ParseText(SourceText.From(sourcesPerProject[i]))],
                [reference],
                new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));
        }

        var loaded = new LoadedSolution { Solution = solution, Compilations = compilations };
        return (loaded, new SymbolResolver(loaded));
    }
}
